/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ICacheGold, ICacheGoldInterface } from "../ICacheGold";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "totalCirculation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class ICacheGold__factory {
  static readonly abi = _abi;
  static createInterface(): ICacheGoldInterface {
    return new utils.Interface(_abi) as ICacheGoldInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICacheGold {
    return new Contract(address, _abi, signerOrProvider) as ICacheGold;
  }
}
