/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IRouterClientInterface extends ethers.utils.Interface {
  functions: {
    "ccipSend(uint64,(bytes,bytes,tuple[],address,bytes))": FunctionFragment;
    "getFee(uint64,(bytes,bytes,tuple[],address,bytes))": FunctionFragment;
    "getSupportedTokens(uint64)": FunctionFragment;
    "isChainSupported(uint64)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ccipSend",
    values: [
      BigNumberish,
      {
        receiver: BytesLike;
        data: BytesLike;
        tokenAmounts: { token: string; amount: BigNumberish }[];
        feeToken: string;
        extraArgs: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getFee",
    values: [
      BigNumberish,
      {
        receiver: BytesLike;
        data: BytesLike;
        tokenAmounts: { token: string; amount: BigNumberish }[];
        feeToken: string;
        extraArgs: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isChainSupported",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ccipSend", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isChainSupported",
    data: BytesLike
  ): Result;

  events: {};
}

export class IRouterClient extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IRouterClientInterface;

  functions: {
    ccipSend(
      destinationChainId: BigNumberish,
      message: {
        receiver: BytesLike;
        data: BytesLike;
        tokenAmounts: { token: string; amount: BigNumberish }[];
        feeToken: string;
        extraArgs: BytesLike;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getFee(
      destinationChainId: BigNumberish,
      message: {
        receiver: BytesLike;
        data: BytesLike;
        tokenAmounts: { token: string; amount: BigNumberish }[];
        feeToken: string;
        extraArgs: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { fee: BigNumber }>;

    getSupportedTokens(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]] & { tokens: string[] }>;

    isChainSupported(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean] & { supported: boolean }>;
  };

  ccipSend(
    destinationChainId: BigNumberish,
    message: {
      receiver: BytesLike;
      data: BytesLike;
      tokenAmounts: { token: string; amount: BigNumberish }[];
      feeToken: string;
      extraArgs: BytesLike;
    },
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getFee(
    destinationChainId: BigNumberish,
    message: {
      receiver: BytesLike;
      data: BytesLike;
      tokenAmounts: { token: string; amount: BigNumberish }[];
      feeToken: string;
      extraArgs: BytesLike;
    },
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getSupportedTokens(
    chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  isChainSupported(
    chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    ccipSend(
      destinationChainId: BigNumberish,
      message: {
        receiver: BytesLike;
        data: BytesLike;
        tokenAmounts: { token: string; amount: BigNumberish }[];
        feeToken: string;
        extraArgs: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    getFee(
      destinationChainId: BigNumberish,
      message: {
        receiver: BytesLike;
        data: BytesLike;
        tokenAmounts: { token: string; amount: BigNumberish }[];
        feeToken: string;
        extraArgs: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSupportedTokens(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    isChainSupported(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    ccipSend(
      destinationChainId: BigNumberish,
      message: {
        receiver: BytesLike;
        data: BytesLike;
        tokenAmounts: { token: string; amount: BigNumberish }[];
        feeToken: string;
        extraArgs: BytesLike;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getFee(
      destinationChainId: BigNumberish,
      message: {
        receiver: BytesLike;
        data: BytesLike;
        tokenAmounts: { token: string; amount: BigNumberish }[];
        feeToken: string;
        extraArgs: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSupportedTokens(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isChainSupported(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ccipSend(
      destinationChainId: BigNumberish,
      message: {
        receiver: BytesLike;
        data: BytesLike;
        tokenAmounts: { token: string; amount: BigNumberish }[];
        feeToken: string;
        extraArgs: BytesLike;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getFee(
      destinationChainId: BigNumberish,
      message: {
        receiver: BytesLike;
        data: BytesLike;
        tokenAmounts: { token: string; amount: BigNumberish }[];
        feeToken: string;
        extraArgs: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSupportedTokens(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isChainSupported(
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
