/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface RedeemTransferInterface extends ethers.utils.Interface {
  functions: {
    "CGT()": FunctionFragment;
    "childTunnelContract()": FunctionFragment;
    "redeemAddr()": FunctionFragment;
    "withdrawAllCGT()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "CGT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "childTunnelContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeemAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAllCGT",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "CGT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "childTunnelContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeemAddr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAllCGT",
    data: BytesLike
  ): Result;

  events: {
    "FundsRedeemed(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FundsRedeemed"): EventFragment;
}

export type FundsRedeemedEvent = TypedEvent<[BigNumber] & { arg0: BigNumber }>;

export class RedeemTransfer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: RedeemTransferInterface;

  functions: {
    CGT(overrides?: CallOverrides): Promise<[string]>;

    childTunnelContract(overrides?: CallOverrides): Promise<[string]>;

    redeemAddr(overrides?: CallOverrides): Promise<[string]>;

    withdrawAllCGT(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  CGT(overrides?: CallOverrides): Promise<string>;

  childTunnelContract(overrides?: CallOverrides): Promise<string>;

  redeemAddr(overrides?: CallOverrides): Promise<string>;

  withdrawAllCGT(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    CGT(overrides?: CallOverrides): Promise<string>;

    childTunnelContract(overrides?: CallOverrides): Promise<string>;

    redeemAddr(overrides?: CallOverrides): Promise<string>;

    withdrawAllCGT(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "FundsRedeemed(uint256)"(
      undefined?: null
    ): TypedEventFilter<[BigNumber], { arg0: BigNumber }>;

    FundsRedeemed(
      undefined?: null
    ): TypedEventFilter<[BigNumber], { arg0: BigNumber }>;
  };

  estimateGas: {
    CGT(overrides?: CallOverrides): Promise<BigNumber>;

    childTunnelContract(overrides?: CallOverrides): Promise<BigNumber>;

    redeemAddr(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawAllCGT(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CGT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    childTunnelContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    redeemAddr(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawAllCGT(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
